//
//  ListMoviesViewController.swift
//  CleanStore
//
//  Created by Felipe Miranda on 10/01/20.
//  Copyright (c) 2020 Felipe Miranda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesDisplayLogic: class {
    func showListMovies(viewModel: ListMovies.Models.ViewModel)
}

class ListMoviesViewController: UIViewController {
    
    
    @IBOutlet weak var listMovieTableView: UITableView! {
        didSet {
            listMovieTableView.delegate = self
            listMovieTableView.dataSource = self
        }
    }
    
    lazy var worker = ListMoviesWorker()
    lazy var viewModel = MoviesViewModel()
    lazy var presenter = ListMoviesPresenter(viewController: self)
    
    lazy var interactor: ListMoviesBusinessLogic = ListMoviesInteractor(presenter: presenter, worker: worker)
    
    override func viewDidLoad(){
        super.viewDidLoad()
        
        interactor.getListMovies()
    }
}

extension ListMoviesViewController: ListMoviesDisplayLogic {
    func showListMovies(viewModel: ListMovies.Models.ViewModel) {
        self.viewModel = viewModel.moviesViewModel
        self.listMovieTableView.reloadData()
    }
}

extension ListMoviesViewController: UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return self.viewModel.numberOfSections
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.viewModel.numberOfRows
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
        cell.textLabel?.text = self.viewModel.title
        
        return cell
    }
    
}

extension ListMoviesViewController: UITableViewDelegate {
    
}
