//
//  ListMoviesPresenter.swift
//  CleanStore
//
//  Created by Felipe Miranda on 10/01/20.
//  Copyright (c) 2020 Felipe Miranda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesPresentationLogic{
    func presentSomething(response: ListMovies.Models.Response)
    func showErrorScreen(error: Error?)
    func displayMovies(movies: Movie)
}

class ListMoviesPresenter: ListMoviesPresentationLogic {
    var viewController: ListMoviesDisplayLogic
    
    init(viewController: ListMoviesDisplayLogic) {
        self.viewController = viewController
    }
    
    // MARK: Do something
    func presentSomething(response: ListMovies.Models.Response){
        
        //let viewModel = ListMovies.Something.ViewModel()
        //viewController?.displaySomething(viewModel: viewModel)
    }
    
    func showErrorScreen(error: Error?) {
        
    }
    
    func displayMovies(movies: Movie) {
        
    }
}
